### PR TITLE
Minor improvements #4 #5

### PR DESCRIPTION
**Pull request by corebonts**

### CODE REVIEW

**Comment by corebonts** [comment]
**Before cell fix:**
image
**After cell fix:**
image
**Before causes fix:**
image
**After causes fix:**
image

**Review by JRJurman — APPROVED** [review]
I no longer am working at a company that uses BlueOcean, but based on your screenshots, this looks great! Thank you for submitting a PR!

**Comment by JRJurman** [comment]
I will publish this momentarily, let me know if there are any issues!

**Comment by corebonts** [comment]
I tested the deployed extension, works fine, thanks!

**Pull request merged**
